### ISSUE TITLE
Need contribution steps

### ISSUE THREAD

**Issue by ArshErgon** [OnCampus-Community/.github#4]
We have a code of conduct but we don't have a file which tells the beginners how to fork the repo, clone it, make a new branch, make changes, push and finally start a PR
Task make a `contributing.md` file with the complete screenshot of the process

**Comment by saakshiraut28** [comment]
Hi, can I work on this issue?

**Comment by ArshErgon** [comment]
@saakshiraut28 sure, and if you need help, feel free to ping me.

**Comment by saakshiraut28** [comment]
Yep, Thanks.
